#Global Variables
aws_owner_tag: sample_owner
aws_access_key: replaced_by_user
aws_secret_key: replaced_by_user

#Platform CFN stack config
vpc_stack_name: "Utils-SimpleVPC-Setup" 

#ECS stack config
ecs_stack_name: "Utils-HelloWorld" 
service_name : HelloWorld
desired_count: 2
container_cpu: 256
container_memory: 512
container_port: 80
docker_image_url: 801357027545.dkr.ecr.eu-west-1.amazonaws.com/utils.helloworld